[package]
name = "twitter-images"
version = "0.1.0"
edition = "2021"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
license = "MIT/Apache-2.0"
description = "Fetch original quality images from the tweets of a given Twitter user"
repository = "https://github.com/msfjarvis/twitter-images"
homepage = "https://github.com/msfjarvis/twitter-images"
keywords = ["twitter", "images"]
readme = "README.md"
include = ["src/main.rs", "LICENSE-*", "README.md"]

[dependencies]
color-eyre = { version = "0.6.0", default-features = false }
egg-mode = { version = "0.16.0", features = ["rustls_webpki"], default-features = false }
tokio = { version = "1.16.0", features = ["rt-multi-thread", "macros"] }
structopt = "0.3.26"
